# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"query_API": "01-retrieval.ipynb",
         "dict_col_to_cols": "01-retrieval.ipynb",
         "clean_nested_dict_cols": "01-retrieval.ipynb",
         "set_dt_idx": "01-retrieval.ipynb",
         "create_df_dt_rng": "01-retrieval.ipynb",
         "clean_df_dts": "01-retrieval.ipynb",
         "retrieve_stream_df": "01-retrieval.ipynb",
         "check_streams": "01-retrieval.ipynb",
         "retrieve_streams_df": "01-retrieval.ipynb",
         "get_EI_data": "01-retrieval.ipynb",
         "bulk_retrieval": "01-retrieval.ipynb",
         "get_EI_files": "01-retrieval.ipynb",
         "check_for_gappy_data": "01-retrieval.ipynb",
         "retrieve_latest_data": "01-retrieval.ipynb",
         "year_to_resource": "01-retrieval.ipynb",
         "construct_datapackage": "01-retrieval.ipynb",
         "app": "01-retrieval.ipynb",
         "download": "01-retrieval.ipynb"}

modules = ["retrieval.py"]

doc_url = "https://AyrtonB.github.io/EI/"

git_url = "https://github.com/AyrtonB/Spotify-Watch"

def custom_doc_links(name): return None
